title: epicene.info
description: Normaliser et faciliter l'usage de l'écriture inclusive
baseurl: /epicene.info
url: https://mattisg.github.io

exclude: [
  build.sh,
  generators,
  google-application-credentials.json,
  node_modules,
  package-lock.json
]
