title: epicene.info
description: "Normaliser et faciliter l'usage de l'écriture inclusive"
url: "https://epicene.info"

exclude: [
  build.sh,
  generators,
  google-application-credentials.json,
  node_modules,
  package-lock.json
]
